create table developers
(
    id          integer generated by default as identity
        constraint developers_pkey
            primary key,
    first_name  varchar(255),
    info        varchar(255),
    last_name   varchar(255),
    middle_name varchar(255)
);

create table games
(
    id               integer generated by default as identity
        constraint games_pkey
            primary key,
    name             varchar(255),
    price            numeric(19, 2),
    publishing_house varchar(255)
);

create table game_has_developer
(
    game_id   integer not null
        constraint fkq7t4b1gg1eqpjo0kom4t8vktl
            references games,
    developer_id integer not null
        constraint fk8oktfipod4dby36a7wj285yn8
            references developers
);

create table categories
(
    id   integer generated by default as identity
        constraint categories_pkey
            primary key,
    name varchar(255)
);

create table game_has_category
(
    game_id     integer not null
        constraint fktoynsl1vx9orlcuol20u48si8
            references games,
    category_id integer not null
        constraint fk5cs1uc6w5jhddv9p4e6kro5hd
            references categories
);

create table clients
(
    id          integer generated by default as identity
        constraint clients_pkey
            primary key,
    address     varchar(255),
    email       varchar(255),
    first_name  varchar(255),
    last_name   varchar(255),
    middle_name varchar(255),
    phone       varchar(255)
);

create table users
(
    id       integer generated by default as identity
        constraint users_pkey
            primary key,
    login    varchar(255),
    password varchar(255)
);

create table accounts
(
    id        integer generated by default as identity
        constraint accounts_pkey
            primary key,
    balance   numeric(19, 2),
    is_active boolean not null,
    client_id integer
        constraint fkgymog7firrf8bnoiig61666ob
            references clients,
    user_id   integer
        constraint fknjuop33mo69pd79ctplkck40n
            references users
);